// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOls2szlh5JnnULtef0-nK6qMhpvfj16E',
    appId: '1:263278452426:web:74e22c3ab15bd627451e33',
    messagingSenderId: '263278452426',
    projectId: 'noteproject-1a0a7',
    authDomain: 'noteproject-1a0a7.firebaseapp.com',
    storageBucket: 'noteproject-1a0a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7KrhKtgDV1yGmYBhyDzWS9sVktG-4EMI',
    appId: '1:263278452426:android:8ddaf6d3433bd6ab451e33',
    messagingSenderId: '263278452426',
    projectId: 'noteproject-1a0a7',
    storageBucket: 'noteproject-1a0a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVykFoLHq0g9NF98k0_ND_BWiiGmQYZTY',
    appId: '1:263278452426:ios:369af24286b699fb451e33',
    messagingSenderId: '263278452426',
    projectId: 'noteproject-1a0a7',
    storageBucket: 'noteproject-1a0a7.appspot.com',
    iosClientId: '263278452426-rfuatt4n2ursllj29ai0jgq0rjli6e0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVykFoLHq0g9NF98k0_ND_BWiiGmQYZTY',
    appId: '1:263278452426:ios:0d25889f0a4ccaa7451e33',
    messagingSenderId: '263278452426',
    projectId: 'noteproject-1a0a7',
    storageBucket: 'noteproject-1a0a7.appspot.com',
    iosClientId: '263278452426-prj2q37ga4mcf8lqqukdhpvg0kem6ubg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
